kind: pipeline
name: node8

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: hypriot/rpi-node:8.1
  commands:
  - npm config set proxy null
  - npm config set https-proxy null
  - npm config set registry <registry url>
  - rm -rf node_modules
  - npm install
  - npm test

settings:
    repo: <repo url>
